# Generated by Django 4.2.3 on 2023-09-04 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("duration", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Playlist_items_Id", new_name="Playlist_Id",),
        migrations.CreateModel(
            name="Playlist_items",
            fields=[
                (
                    "video_Id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("thumbnail", models.CharField(max_length=240)),
                (
                    "playlist_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="duration.playlist_id",
                    ),
                ),
            ],
        ),
    ]
